# Reverse-proxy vhost for __FQDN__  (generated by new-app.sh — do not hand-edit;
# re-run new-app.sh to regenerate). certbot adds the matching :443 vhost + the
# HTTP->HTTPS redirect when it issues the certificate.
<VirtualHost *:80>
    ServerName __FQDN__

    ProxyPreserveHost On
    ProxyRequests Off

    # The app sits behind TLS once certbot runs; tell it so it sets secure cookies.
    RequestHeader set X-Forwarded-Proto "https"

    # Proxy to the app's loopback-only port on the host.
    ProxyPass        /  http://127.0.0.1:__PORT__/  retry=0
    ProxyPassReverse /  http://127.0.0.1:__PORT__/

    ErrorLog  ${APACHE_LOG_DIR}/__APP___error.log
    CustomLog ${APACHE_LOG_DIR}/__APP___access.log combined
</VirtualHost>
